name: Push snap

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which version to publish to snapstore'
        required: true

env:
  CI: true
  SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.1
        with:
          envFilePath: ./envvars.for.actions

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install
        run: npm install --legacy-peer-deps

      - name: build
        run: npm run build

      - name: package
        run: npm run package

      - name: publish snap
        uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: "dist/text-tool_${{ github.event.inputs.version }}_amd64.snap"
          release: beta,candidate,stable
